--CRIA BASE DE DADOS
CREATE DATABASE CONTA_LUZ_DB;

--CRIA TABELA
USE CONTA_LUZ_DB 
CREATE TABLE GASTO (
    DT_LEITURA DATE NOT NULL,
    NUMERO_LEITURA INT NOT NULL,
    QTD_KW_GASTO FLOAT NOT NULL,
    DATA_PAGAMENTO DATE NOT NULL,
    MEDIA_CONSUMO FLOAT
);

SELECT * FROM GASTO;

--ALTERA COLUNAS
EXEC sp_rename 'GASTO.DT_LEITURA', 'DATA_LEITURA', 'COLUMN';
EXEC sp_rename 'GASTO.QTD_KW_GASTO', 'QUANTIDADE_KW_GASTO', 'COLUMN';

--ALTERA TIPO COLUNAS
ALTER TABLE GASTO ALTER COLUMN
    NUMERO_LEITURA BIGINT NOT NULL;	
ALTER TABLE GASTO ALTER COLUMN
    DATA_PAGAMENTO DATETIME NOT NULL;

--EXCLUI COLUNAS
ALTER TABLE GASTO DROP COLUMN DATA_LEITURA;
ALTER TABLE GASTO DROP COLUMN NUMERO_LEITURA;
ALTER TABLE GASTO DROP COLUMN DATA_PAGAMENTO;
ALTER TABLE GASTO DROP COLUMN QUANTIDADE_KW_GASTO;
ALTER TABLE GASTO DROP COLUMN MEDIA_CONSUMO;

-- EXCLUI TABELA
DROP TABLE GASTO;

-- EXCLUI BANCO DE DADOS
DROP DATABASE CONTA_LUZ_DB;