--CRIA BASE DE DADOS
CREATE DATABASE HOSPITAL_DB;

--CRIA TABELA
USE HOSPITAL_DB
CREATE TABLE PRESCRICAO_REMEDIO(  
    USUARIO VARCHAR(200) NOT NULL  
    ,DATA_INICIO DATE NOT NULL  
    ,QTD_DIAS INT NOT NULL 
    ,QTD_VEZES_DIA INT NOT NULL
    ,DOSAGEM FLOAT NOT NULL  
    ,REMEDIO VARCHAR(200) NULL  
    ,HORARIO DATETIME NOT NULL  
);

SELECT * FROM PRESCRICAO_REMEDIO;

--ALTERAÇÃO DA TABELA NOME

EXEC sp_rename 'PRESCRICAO_REMEDIO.QTD_DIAS', 'QUANTIDADE_DIAS', 'COLUMN';
EXEC sp_rename 'PRESCRICAO_REMEDIO.QTD_VEZES_DIA ', 'QUANTIDADE_VEZES_DIA', 'COLUMN';

--ALTERA DA TABELA TIPO
ALTER TABLE PRESCRICAO_REMEDIO ALTER COLUMN
    DOSAGEM VARCHAR(255) NOT NULL;
ALTER TABLE PRESCRICAO_REMEDIO ALTER COLUMN
    REMEDIO VARCHAR(255) NOT NULL;

--EXCLUI COLUNA
ALTER TABLE PRESCRICAO_REMEDIO DROP USUARIO;
ALTER TABLE PRESCRICAO_REMEDIO DROP DATA_INICIO;
ALTER TABLE PRESCRICAO_REMEDIO DROP QUANTIDADE_DIAS;
ALTER TABLE PRESCRICAO_REMEDIO DROP QUANTIDADE_VEZES_DIA;
ALTER TABLE PRESCRICAO_REMEDIO DROP DOSAGEM;
ALTER TABLE PRESCRICAO_REMEDIO DROP REMEDIO;
ALTER TABLE PRESCRICAO_REMEDIO DROP HORARIO;

-- EXCLUI TABELA
DROP TABLE PRESCRICAO_REMEDIO;

-- EXCLUI BANCO DE DADOS
DROP DATABASE HOSPITAL_DB