-- CRIA BASE DE DADOS
CREATE DATABASE SALA_REUNIAO_DB;

-- CRIA TABELA
USE SALA_REUNIAO_DB
CREATE TABLE ALOCACAO_SALA (
	SALA VARCHAR(100) NOT NULL,
	DATA_ALOCACAO DATE NOT NULL,
	HORA_INICIO DATETIME NOT NULL,
	HORA_FIM DATETIME NOT NULL,
	RESPONSAVEL VARCHAR(200) NULL
) 

SELECT * FROM ALOCACAO_SALA;

--RENOMEIA COLUNA
EXEC sp_rename 'ALOCACAO_SALA.SALA', 'SALA_REUNIAO', 'COLUMN';
EXEC sp_rename 'ALOCACAO_SALA.DT_ALOCACAO ', 'DATA_ALOCACAO', 'COLUMN';

--ALTERA TIPO COLUNA
ALTER TABLE ALOCACAO_SALA ALTER COLUMN
    DATA_ALOCACAO DATETIME NOT NULL;
ALTER TABLE ALOCACAO_SALA ALTER COLUMN
    HORA_FIM DATETIME NOT NULL;

--EXCLUINDO COLUNA
ALTER TABLE ALOCACAO_SALA DROP SALA_REUNIAO;
ALTER TABLE ALOCACAO_SALA DROP DATA_ALOCACAO;
ALTER TABLE ALOCACAO_SALA DROP HORA_INICIO;
ALTER TABLE ALOCACAO_SALA DROP HORA_FIM;
ALTER TABLE ALOCACAO_SALA DROP RESPONSAVEL;

-- EXCLUINDO TABELA
DROP TABLE ALOCACAO_SALA;

-- EXCLUINDO BANCO DE DADOS
DROP DATABASE SALA_REUNIAO_DB;